variables:
  WEBAPPS: /home/http_service/tomcat/webapps #发布服务器地址
  PROJECT: $WEBAPPS/$CI_PROJECT_NAME #发布服务目录
stages:
  - build
  - deploy
build: # 编译
  stage: build
  only:
    - master
  script:
    - echo "I am install"
    - cd documents
    - npm install
    - npm run build
    - echo "I am deploy"
    - PROJECT=${PROJECT//-/_};if [ ! -d $PROJECT ]; then mkdir -p $PROJECT;echo "mkdir ${PROJECT}"; else rm -rf ${PROJECT}/* ;echo "rm ${PROJECT}"; fi #如果目录不存在创建否则删除
    - echo $PROJECT
    - mv docs/.vuepress/dist/* $PROJECT #部署文件