language: node_js
node_js:
    - 8
cache: npm
install:
|
    npm install -g npm@latest
    npm --version
    npm install --registry http://registry.npmjs.org
script:
    - npm link
    - x-build create demo -q
