language: node_js
sudo: required
node_js:
    - 10
cache: yarn  
install:
    - npm install -g npm@latest
    - npm --version
    - npm install --registry http://registry.npmjs.org
    - npm install -g codecov
    - npm install -g yarn
script:
    - npm link
    - x create test -q
    - cd test && ls -l
    - cat package.json
    - cat xbuild-config.js
    - cd src && ls -l

