language: node_js
sudo: required
node_js:
    - 8
    - 10
cache: yarn  
install:
    - yarn
script:
    - npm link
    - mkdir bs && cd bs && x test bs
    - mkdir pug && cd pug  && x test pug
    - mkdir mobileLayout && cd mobileLayout  && x test mobileLayout
    - mkdir sass && cd sass  && x test sass
    - mkdir less && cd less  && x test less
    - mkdir stylus && cd stylus  && x test stylus