language: node_js
sudo: required
node_js:
    - 8
    - 10
cache: yarn  
install:
    - yarn
script:
    - npm link
    - mkdir bs && x test bs
    - mkdir pug && x test pug
    - mkdir mobileLayout && x test mobileLayout
    - mkdir sass && x test sass
    - mkdir less && x test less
    - mkdir stylus && x test stylus