language: node_js
sudo: required
node_js:
    - 10
cache: yarn  
install:
    - yarn
script:
    - npm link
    - x create test -q
    - cd test && ls -l
    - cat package.json
    - cat xbuild.config.js
    - cd src && ls -l
