language: node_js
sudo: required
node_js:
    - 8
    - 10
cache: yarn  
install:
    - yarn
script:
    - npm link
    - mkdir bs && x create bs
    - mkdir pug && x create pug
    - mkdir mobileLayout && x create mobileLayout
    - mkdir sass && x create sass
    - mkdir less && x create less
    - mkdir stylus && x create stylus